
" Load all plugins
source ~/.vim/vim-plug.vim

" Vim basic configuration.
source ~/.vim/config.vim

" Functions
source ~/.vim/functions.vim

" All hotkeys, not dependant on plugins, are mapped here.
source ~/.vim/mappings.vim

" Plugin-specific configuration.
 source ~/.vim/plugins.vim

" Abbreviations
source ~/.vim/abbrev.vim

" Autogroup/autocmd
source ~/.vim/augroup.vim"

" Local overrides
if filereadable(glob("~/.vim_local/vimrc"))
    exe 'set rtp+=' .expand('~/.vim_local')
    source ~/.vim_local/vimrc
endif
