
" Load all plugins
source ~/.vim/vim-plug.vim

" Vim basic configuration.
source ~/.vim/config.vim

" Functions
source ~/.vim/functions.vim

" All hotkeys, not dependant on plugins, are mapped here.
source ~/.vim/mappings.vim

" Plugin-specific configuration.
 source ~/.vim/plugins.vim

" Abbreviations
source ~/.vim/abbrev.vim

" Autogroup/autocmd
source ~/.vim/augroup.vim"

" Local overrides
if filereadable(glob("~/.vim.local/vimrc"))
    exe 'set rtp+=' .expand('~/.vim.local')
    " after changing your 'runtimepath', which would first unset the
    " filetype-detection autocommands, and then re-source to set
    " them again with the new 'runtimepath'
    filetype off
    filetype plugin indent on
    source ~/.vim.local/vimrc
endif
