#!/bin/bash

alias ..="cd .."
alias cd..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias isvm='dmesg --notime | grep -i hypervisor | cut -d ':' -f2 | tr -d " \t\n\r"'
#alias gcurl='curl --http1.1 -H "$(docker run -v ~/.gcp:/gcp -it gcr.io/oauth2l/oauth2l header --json /gcp/key.json cloud-platform)" -H "Content-Type: application/json" '
alias gcurl='curl --header "Authorization: Bearer $(gcloud auth print-identity-token)"'
alias screenshot='grim -g "$(slurp)" ~/Downloads/screenshot-`date +%F-%T`.png'
