#!/bin/bash

# bash completion is sorted by /etc/bash.bashrc
# that is loaded automatically.

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f /usr/share/fzf/key-bindings.bash ]; then
   . /usr/share/fzf/key-bindings.bash
   . /usr/share/fzf/completion.bash
fi
