#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Human readable file size
# (because `du -h` doesn't cut it for me)

hrfs() {

    printf "%s" "$1" |
    awk '{
            i = 1;
            split("B KB MB GB TB PB EB ZB YB WTFB", v);
            value = $1;
            # confirm that the input is a number
            if ( value + .0 == value ) {
                while ( value >= 1024 ) {
                    value/=1024;
                    i++;
                }
                if ( value == int(value) ) {
                    printf "%d %s", value, v[i]
                } else {
                    printf "%.1f %s", value, v[i]
                }
            }
        }' |
    sed -e ":l" \
        -e "s/\([0-9]\)\([0-9]\{3\}\)/\1,\2/; t l"
    #    └─ add thousands separator
    #       (changes "1023.2 KB" to "1,023.2 KB")
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create new directories and enter the first one

mkd() {
    if [ -n "$*" ]; then

        mkdir -p "$@"
        #      └─ make parent directories if needed

        cd "$@" \
            || exit 1

    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Search for text within the current directory

qt() {
    grep -ir --color=always "$*" . | less -RX
    #     │└─ search all files under each directory, recursively
    #     └─ ignore case
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Pomodoro countdown
# Takes optional duration number in minutes
# https://en.wikipedia.org/wiki/Pomodoro_Technique
pomodoro() {
    duration_sec=$((60*${1:-25})) #convert to seconds
    pomodoro_end=$((`date +%s` + ${duration_sec}))
    while [ "${pomodoro_end}" -ge `date +%s` ]; do
        echo -ne "$(date -u --date @$((${pomodoro_end} - `date +%s`)) +%M:%S)\r"
        sleep 0.2
    done
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# CSV viewer
tableview() {
    column -s, -t < $1 | less -#4 -N -S
}

# Screen brightness
backlight() {
    echo $1 | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null
}

# Returns difference in days between two dates. Example:
# $ datediff '1 Nov' '1 Aug'
# 91 days
datediff() {
    d1=$(date -d "$1" +%s)
    d2=$(date -d "$2" +%s)
    echo $(( (d1 - d2) / 86400 )) days
}

# Rebases chain of branches
# git rebase master branch1
# rebase-chain branch2 branch3
rebase-chain() {
  for i in ${@}; do
    git rebase --onto HEAD ORIG_HEAD $i || break
  done
}
