#!/bin/bash

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f /usr/share/fzf/key-bindings.bash ]; then
   . /usr/share/fzf/key-bindings.bash
   . /usr/share/fzf/completion.bash
fi
